const express = require("express");
const app = express();
const path = require("path");
const bodyParser = require("body-parser");
const hbs = require("hbs");

const port = process.env.PORT || 3000;

const publicDirectoryPath = path.join(__dirname, "../public");
const viewsPath = path.join(__dirname, "../views"); // Views folder where templates are stored

// Set up handlebar as the template engine
app.set("view engine", "hbs");

app.set("views", viewsPath);

// Serve static files (CSS)
app.use(express.static(publicDirectoryPath));

// Middleware to parse the form data
app.use(express.urlencoded({ extended: true }));
// Use bodyParser middleware to parse POST request data
app.use(bodyParser.urlencoded({ extended: true }));

// Salary data: Employee salaries

const employees = [
  {
    Emp_id: "4",
    Emp_Photo: "Upload\\Emp_Photo\\LwvvBlaFg8gu1LCDJhuaVishnu Kumar.jpg",
    EmpName_title: "Mr.",
    EmpName: "Vishnu Kumar",
    Department_id: "3",
    DepartmentName: "PRODUCT",
    designation_id: "15",
    designationName: "SOFTWARE ENGINEER",
    officeEmail: "Vishnu.k@iglgenesis.com",
    Mobile: "9315753988",
    isworking: "Yes",
    Company_id: "1",
    CompanyName: "IGL Genesis Technologies Ltd",
    Company_Address_id: "2",
    Title: "Head Office",
    Line1: "10 DDA Commercial Complex",
    Line2: "",
    Land_MarK: "Nangal Raya",
    Country_id: "86",
    CountryName: "India",
    State_id: "10",
    state_name: "Delhi",
    City_id: "162",
    City_Name: "Delhi",
    PinCode: "110046",
    EmployeesType: "1",
    EmpCode: "IGTL/23/0020",
  },
  {
    Emp_id: "14",
    Emp_Photo: "",
    EmpName_title: "Mr.",
    EmpName: "ANUP SRIVASTAVA",
    Department_id: "3",
    DepartmentName: "PRODUCT",
    designation_id: "4",
    designationName: "PRODUCT HEAD",
    officeEmail: "anup.s@iglgenesis.com",
    Mobile: "8743828333",
    isworking: "Yes",
    Company_id: "1",
    CompanyName: "IGL Genesis Technologies Ltd",
    Company_Address_id: "2",
    Title: "Head Office",
    Line1: "10 DDA Commercial Complex",
    Line2: "",
    Land_MarK: "Nangal Raya",
    Country_id: "86",
    CountryName: "India",
    State_id: "10",
    state_name: "Delhi",
    City_id: "162",
    City_Name: "Delhi",
    PinCode: "110046",
    EmployeesType: "1",
    EmpCode: "IGTL/23/0005",
    Lat: "28.6116283",
    Lon: "77.1097795",
  },
  {
    Emp_id: "15",
    Emp_Photo: "Upload\\Emp_Photo\\uIQCDdclrpCPMtvM3vp8DHIRAJ TIWARY.jpg",
    EmpName_title: "Mr.",
    EmpName: "DHIRAJ TIWARY",
    Department_id: "4",
    DepartmentName: "PROJECT",
    designation_id: "5",
    designationName: "PROJECT HEAD",
    officeEmail: "dhiraj@iglgenesis.com",
    Mobile: "8745943900",
    isworking: "Yes",
    Company_id: "1",
    CompanyName: "IGL Genesis Technologies Ltd",
    Company_Address_id: "2",
    Title: "Head Office",
    Line1: "10 DDA Commercial Complex",
    Line2: "",
    Land_MarK: "Nangal Raya",
    Country_id: "86",
    CountryName: "India",
    State_id: "10",
    state_name: "Delhi",
    City_id: "162",
    City_Name: "Delhi",
    PinCode: "110046",
    EmployeesType: "1",
    EmpCode: "IGTL/23/0006",
    Lat: "28.6116283",
    Lon: "77.1097795",
  },
  {
    Emp_id: "16",
    Emp_Photo: "",
    EmpName_title: "Mr.",
    EmpName: "KRISHNA PR SINGH",
    Department_id: "4",
    DepartmentName: "PROJECT",
    designation_id: "6",
    designationName: "PROJECT ADMINISTRATOR",
    officeEmail: "krishna.s@iglgenesis.com",
    Mobile: "9717744542",
    isworking: "Yes",
    Company_id: "1",
    CompanyName: "IGL Genesis Technologies Ltd",
    Company_Address_id: "2",
    Title: "Head Office",
    Line1: "10 DDA Commercial Complex",
    Line2: "",
    Land_MarK: "Nangal Raya",
    Country_id: "86",
    CountryName: "India",
    State_id: "10",
    state_name: "Delhi",
    City_id: "162",
    City_Name: "Delhi",
    PinCode: "110046",
    EmployeesType: "1",
    EmpCode: "IGTL/23/0007",
    Lat: "28.6116283",
    Lon: "77.1097795",
  },
  {
    Emp_id: "17",
    Emp_Photo: "",
    EmpName_title: "Mr.",
    EmpName: "VIVEK RAJ",
    Department_id: "5",
    DepartmentName: "FINANCE",
    designation_id: "7",
    designationName: "FINANCE HEAD",
    officeEmail: "finance@iglgenesis.com",
    Mobile: "8010147500",
    isworking: "Yes",
    Company_id: "1",
    CompanyName: "IGL Genesis Technologies Ltd",
    Company_Address_id: "2",
    Title: "Head Office",
    Line1: "10 DDA Commercial Complex",
    Line2: "",
    Land_MarK: "Nangal Raya",
    Country_id: "86",
    CountryName: "India",
    State_id: "10",
    state_name: "Delhi",
    City_id: "162",
    City_Name: "Delhi",
    PinCode: "110046",
    EmployeesType: "1",
    EmpCode: "IGTL/23/0008",
    Lat: "28.6116283",
    Lon: "77.1097795",
  },
  {
    Emp_id: "18",
    Emp_Photo: "",
    EmpName_title: "Mr.",
    EmpName: "MOHAMMAD SAIRAB",
    Department_id: "3",
    DepartmentName: "PRODUCT",
    designation_id: "8",
    designationName: "SR SOFTWARE ENGINEER",
    officeEmail: "mohd.s@iglgenesis.com",
    Mobile: "8744945844",
    isworking: "Yes",
    Company_id: "1",
    CompanyName: "IGL Genesis Technologies Ltd",
    Company_Address_id: "2",
    Title: "Head Office",
    Line1: "10 DDA Commercial Complex",
    Line2: "",
    Land_MarK: "Nangal Raya",
    Country_id: "86",
    CountryName: "India",
    State_id: "10",
    state_name: "Delhi",
    City_id: "162",
    City_Name: "Delhi",
    PinCode: "110046",
    EmployeesType: "1",
    EmpCode: "IGTL/23/0009",
    Lat: "28.6116283",
    Lon: "77.1097795",
  },
  {
    Emp_id: "19",
    Emp_Photo: "",
    EmpName_title: "Mr.",
    EmpName: "UTKARSH",
    Department_id: "3",
    DepartmentName: "PRODUCT",
    designation_id: "9",
    designationName: "SAP ABAP CONSULTANT",
    officeEmail: "utkarsh@iglgenesis.com",
    Mobile: "8130600678",
    isworking: "Yes",
    Company_id: "1",
    CompanyName: "IGL Genesis Technologies Ltd",
    Company_Address_id: "2",
    Title: "Head Office",
    Line1: "10 DDA Commercial Complex",
    Line2: "",
    Land_MarK: "Nangal Raya",
    Country_id: "86",
    CountryName: "India",
    State_id: "10",
    state_name: "Delhi",
    City_id: "162",
    City_Name: "Delhi",
    PinCode: "110046",
    EmployeesType: "1",
    EmpCode: "IGTL/23/0010",
    Lat: "28.6116283",
    Lon: "77.1097795",
  },
  {
    Emp_id: "20",
    Emp_Photo: "Upload\\Emp_Photo\\AHM8TkTfjEznhUrkfBBmVISHAL.jpg",
    EmpName_title: "Mr.",
    EmpName: "VISHAL",
    Department_id: "3",
    DepartmentName: "PRODUCT",
    designation_id: "10",
    designationName: "EMBEDDED ENGINEER",
    officeEmail: "vishal.d@iglgenesis.com",
    Mobile: "9467005468",
    isworking: "Yes",
    Company_id: "1",
    CompanyName: "IGL Genesis Technologies Ltd",
    Company_Address_id: "2",
    Title: "Head Office",
    Line1: "10 DDA Commercial Complex",
    Line2: "",
    Land_MarK: "Nangal Raya",
    Country_id: "86",
    CountryName: "India",
    State_id: "10",
    state_name: "Delhi",
    City_id: "162",
    City_Name: "Delhi",
    PinCode: "110046",
    EmployeesType: "1",
    EmpCode: "IGTL/23/0011",
    Lat: "28.6116283",
    Lon: "77.1097795",
  },
  {
    Emp_id: "21",
    Emp_Photo: "",
    EmpName_title: "Mrs.",
    EmpName: "SONIA",
    Department_id: "6",
    DepartmentName: "HR",
    designation_id: "11",
    designationName: "HR GENERALIST",
    officeEmail: "hr@iglgenesis.com",
    Mobile: "9716226555",
    isworking: "Yes",
    Company_id: "1",
    CompanyName: "IGL Genesis Technologies Ltd",
    Company_Address_id: "2",
    Title: "Head Office",
    Line1: "10 DDA Commercial Complex",
    Line2: "",
    Land_MarK: "Nangal Raya",
    Country_id: "86",
    CountryName: "India",
    State_id: "10",
    state_name: "Delhi",
    City_id: "162",
    City_Name: "Delhi",
    PinCode: "110046",
    EmployeesType: "1",
    EmpCode: "IGTL/23/0013",
    Lat: "28.6116283",
    Lon: "77.1097795",
  },
  {
    Emp_id: "22",
    Emp_Photo: "Upload\\Emp_Photo\\XX3b3EBuDpn2WlloE4nGPARAS RAJORA.jpg",
    EmpName_title: "Mr.",
    EmpName: "PARAS RAJORA",
    Department_id: "3",
    DepartmentName: "PRODUCT",
    designation_id: "12",
    designationName: "ANDROID DEVELOPER",
    officeEmail: "paras.r@iglgenesis.com",
    Mobile: "9654555355",
    isworking: "Yes",
    Company_id: "1",
    CompanyName: "IGL Genesis Technologies Ltd",
    Company_Address_id: "2",
    Title: "Head Office",
    Line1: "10 DDA Commercial Complex",
    Line2: "",
    Land_MarK: "Nangal Raya",
    Country_id: "86",
    CountryName: "India",
    State_id: "10",
    state_name: "Delhi",
    City_id: "162",
    City_Name: "Delhi",
    PinCode: "110046",
    EmployeesType: "1",
    EmpCode: "IGTL/23/0014",
    Lat: "28.6116283",
    Lon: "77.1097795",
  },
  {
    Emp_id: "23",
    Emp_Photo: "",
    EmpName_title: "Mrs.",
    EmpName: "NIGAM RANI",
    Department_id: "3",
    DepartmentName: "PRODUCT",
    designation_id: "12",
    designationName: "ANDROID DEVELOPER",
    officeEmail: "nigam.r@iglgenesis.com",
    Mobile: "9540716045",
    isworking: "Yes",
    Company_id: "1",
    CompanyName: "IGL Genesis Technologies Ltd",
    Company_Address_id: "2",
    Title: "Head Office",
    Line1: "10 DDA Commercial Complex",
    Line2: "",
    Land_MarK: "Nangal Raya",
    Country_id: "86",
    CountryName: "India",
    State_id: "10",
    state_name: "Delhi",
    City_id: "162",
    City_Name: "Delhi",
    PinCode: "110046",
    EmployeesType: "1",
    EmpCode: "IGTL/23/0015",
    Lat: "28.6116283",
    Lon: "77.1097795",
  },
  {
    Emp_id: "24",
    Emp_Photo: "Upload\\Emp_Photo\\HyfrANRBE83lQuzaTZDdSOHAN SINGH.jpg",
    EmpName_title: "Mr.",
    EmpName: "SOHAN SINGH",
    Department_id: "5",
    DepartmentName: "FINANCE",
    designation_id: "13",
    designationName: "SENIOR EXECUTIVE ACCOUNTS",
    officeEmail: "accounts@iglgenesis.com",
    Mobile: "9958186909",
    isworking: "Yes",
    Company_id: "1",
    CompanyName: "IGL Genesis Technologies Ltd",
    Company_Address_id: "2",
    Title: "Head Office",
    Line1: "10 DDA Commercial Complex",
    Line2: "",
    Land_MarK: "Nangal Raya",
    Country_id: "86",
    CountryName: "India",
    State_id: "10",
    state_name: "Delhi",
    City_id: "162",
    City_Name: "Delhi",
    PinCode: "110046",
    EmployeesType: "1",
    EmpCode: "IGTL/23/0016",
    Lat: "28.6116283",
    Lon: "77.1097795",
  },
  {
    Emp_id: "25",
    Emp_Photo: "",
    EmpName_title: "Mr.",
    EmpName: "DEEPAK PATRA",
    Department_id: "3",
    DepartmentName: "PRODUCT",
    designation_id: "10",
    designationName: "EMBEDDED ENGINEER",
    officeEmail: "deepak.p@iglgenesis.com",
    Mobile: "8700739043",
    isworking: "Yes",
    Company_id: "1",
    CompanyName: "IGL Genesis Technologies Ltd",
    Company_Address_id: "2",
    Title: "Head Office",
    Line1: "10 DDA Commercial Complex",
    Line2: "",
    Land_MarK: "Nangal Raya",
    Country_id: "86",
    CountryName: "India",
    State_id: "10",
    state_name: "Delhi",
    City_id: "162",
    City_Name: "Delhi",
    PinCode: "110046",
    EmployeesType: "1",
    EmpCode: "IGTL/23/0017",
    Lat: "28.6116283",
    Lon: "77.1097795",
  },
  {
    Emp_id: "26",
    Emp_Photo: "Upload\\Emp_Photo\\rcbgn884TCcnZKLrJVvMVIVEK SHARMA.jpg",
    EmpName_title: "Mr.",
    EmpName: "VIVEK SHARMA",
    Department_id: "3",
    DepartmentName: "PRODUCT",
    designation_id: "14",
    designationName: "WEB DEVELOPER",
    officeEmail: "vivek.s@iglgenesis.com",
    Mobile: "",
    isworking: "Yes",
    Company_id: "1",
    CompanyName: "IGL Genesis Technologies Ltd",
    Company_Address_id: "2",
    Title: "Head Office",
    Line1: "10 DDA Commercial Complex",
    Line2: "",
    Land_MarK: "Nangal Raya",
    Country_id: "86",
    CountryName: "India",
    State_id: "10",
    state_name: "Delhi",
    City_id: "162",
    City_Name: "Delhi",
    PinCode: "110046",
    EmployeesType: "1",
    EmpCode: "IGTL/23/0018",
    Lat: "28.6116283",
    Lon: "77.1097795",
  },
  {
    Emp_id: "28",
    Emp_Photo: "Upload\\Emp_Photo\\bm7glsw8kRbOFmlctq1KRITIKA TIWARI.jpg",
    EmpName_title: "Ms.",
    EmpName: "RITIKA TIWARI",
    Department_id: "3",
    DepartmentName: "PRODUCT",
    designation_id: "15",
    designationName: "SOFTWARE ENGINEER",
    officeEmail: "ritika.t@iglgenesis.com",
    Mobile: "7800493340",
    isworking: "Yes",
    Company_id: "1",
    CompanyName: "IGL Genesis Technologies Ltd",
    Company_Address_id: "2",
    Title: "Head Office",
    Line1: "10 DDA Commercial Complex",
    Line2: "",
    Land_MarK: "Nangal Raya",
    Country_id: "86",
    CountryName: "India",
    State_id: "10",
    state_name: "Delhi",
    City_id: "162",
    City_Name: "Delhi",
    PinCode: "110046",
    EmployeesType: "1",
    EmpCode: "IGTL/23/0021",
    Lat: "28.6116283",
    Lon: "77.1097795",
  },
  {
    Emp_id: "32",
    Emp_Photo: "",
    EmpName_title: "Ms.",
    EmpName: "KANIKA SHISHODIA",
    Department_id: "3",
    DepartmentName: "PRODUCT",
    designation_id: "15",
    designationName: "SOFTWARE ENGINEER",
    officeEmail: "kanika.s@iglgenesis.com",
    Mobile: "8630906945",
    isworking: "Yes",
    Company_id: "1",
    CompanyName: "IGL Genesis Technologies Ltd",
    Company_Address_id: "2",
    Title: "Head Office",
    Line1: "10 DDA Commercial Complex",
    Line2: "",
    Land_MarK: "Nangal Raya",
    Country_id: "86",
    CountryName: "India",
    State_id: "10",
    state_name: "Delhi",
    City_id: "162",
    City_Name: "Delhi",
    PinCode: "110046",
    EmployeesType: "1",
    EmpCode: "IGTL/23/0023",
    Lat: "28.6116283",
    Lon: "77.1097795",
  },
  {
    Emp_id: "33",
    Emp_Photo: "Upload\\Emp_Photo\\CODIMb5oSanRAdDU2ZYsJustGLogo2.png",
    EmpName_title: "Mr.",
    EmpName: "GAURAV SHARMA",
    Department_id: "3",
    DepartmentName: "PRODUCT",
    designation_id: "18",
    designationName: "WEB DESIGNER",
    officeEmail: "gaurav.s@iglgenesis.com",
    Mobile: "8750266267",
    isworking: "Yes",
    Company_id: "1",
    CompanyName: "IGL Genesis Technologies Ltd",
    Company_Address_id: "2",
    Title: "Head Office",
    Line1: "10 DDA Commercial Complex",
    Line2: "",
    Land_MarK: "Nangal Raya",
    Country_id: "86",
    CountryName: "India",
    State_id: "10",
    state_name: "Delhi",
    City_id: "162",
    City_Name: "Delhi",
    PinCode: "110046",
    EmployeesType: "1",
    EmpCode: "IGTL/23/0024",
    Lat: "28.6116283",
    Lon: "77.1097795",
  },
  {
    Emp_id: "34",
    Emp_Photo:
      "Upload\\Emp_Photo\\jZew4tYeUBwX1YMXute3harsh without background.jpg",
    EmpName_title: "Mr.",
    EmpName: "HARSH PRATAP",
    Department_id: "3",
    DepartmentName: "PRODUCT",
    designation_id: "15",
    designationName: "SOFTWARE ENGINEER",
    officeEmail: "harsh.p@iglgenesis.com",
    Mobile: "7060866287",
    isworking: "Yes",
    Company_id: "1",
    CompanyName: "IGL Genesis Technologies Ltd",
    Company_Address_id: "2",
    Title: "Head Office",
    Line1: "10 DDA Commercial Complex",
    Line2: "",
    Land_MarK: "Nangal Raya",
    Country_id: "86",
    CountryName: "India",
    State_id: "10",
    state_name: "Delhi",
    City_id: "162",
    City_Name: "Delhi",
    PinCode: "110046",
    EmployeesType: "1",
    EmpCode: "IGTL/23/0025",
    Lat: "28.6116283",
    Lon: "77.1097795",
  },
  {
    Emp_id: "57",
    Emp_Photo: "",
    EmpName_title: "Mrs.",
    EmpName: "Anjali Sharma",
    Department_id: "5",
    DepartmentName: "FINANCE",
    designation_id: "31",
    designationName: "Company Secretary & Legal Compliance Officer",
    officeEmail: "cs@iglgenesis.com",
    Mobile: "",
    isworking: "Yes",
    Company_id: "1",
    CompanyName: "IGL Genesis Technologies Ltd",
    Company_Address_id: "2",
    Title: "Head Office",
    Line1: "10 DDA Commercial Complex",
    Line2: "",
    Land_MarK: "Nangal Raya",
    Country_id: "86",
    CountryName: "India",
    State_id: "10",
    state_name: "Delhi",
    City_id: "162",
    City_Name: "Delhi",
    PinCode: "110046",
    EmployeesType: "1",
    EmpCode: "IGTL/24/0044",
    Lat: "28.6116283",
    Lon: "77.1097795",
  },
];

// Register a custom Handlebars helper to compare values
hbs.registerHelper("ifEquals", function (value1, value2, options) {
  if (value1 === value2) {
    console.log("value1", value1);
    return options.fn(this); //Return the content inside the block if true
  } else {
    return options.inverse(this); // Return the inverse if false
  }
});

// Route to render the initial page with a form
app.get("/", (req, res) => {
  // Render the page with the selected salary details
  const employeeID = 0;
  res.render("index", {
    employees,
    employeeID,
  });
});

// Route to handle form submission and show salary details
app.post("/view-salary", (req, res) => {
  const { employee, month, year } = req.body;
  //console.log(req.body);
  // Convert string values to numbers
  const empId = parseInt(employee);
  const monthId = parseInt(month);
  const yearId = parseInt(year);

  //fetch data from api
  fetch(
    `http://103.234.185.128/EDDynamics/api/Get_SalarySlip_Data?emp_id=${empId}&month_id=${monthId}&year_id=${yearId}`
  ).then((response) => {
    response.json().then((data) => {
      const basic = data.salarySlipData[0].basic;
      const hra = data.salarySlipData[0].hra;
      const earnGross = data.salarySlipData[0].earnGross;
      const allowance = data.salarySlipData[0].allowance;
      const totalEarnGross = data.salarySlipData[0].totalEarnGross;
      const pf = data.salarySlipData[0].pf;
      const epf = data.salarySlipData[0].epf_ER;
      const otherDeduction = data.salarySlipData[0].totalDeduction;
      const totalDeduction = otherDeduction + pf;
      const netPay = data.salarySlipData[0].netPay;
      const totalCTC = data.salarySlipData[0].totalCTC;
      const employeeID = empId;
      res.render("index", {
        employees,
        data,
        basic,
        hra,
        earnGross,
        allowance,
        totalEarnGross,
        totalCTC,
        pf,
        epf,
        totalDeduction,
        netPay,
        employeeID,
        employeeNames: data.salarySlipData[0].EmpName,
        selectedEmployee: data.salarySlipData[0].EmpName,
        selectedMonth: data.salarySlipData[0].MonthName,
        selectedYear: data.salarySlipData[0].YearNo,
      });
    });
  });
});

// Start the server
app.listen(port, () => {
  console.log("Server is running on port " + port);
});
